// ============================================
// Football Principle Lab — Articles Data
// ============================================

const ARTICLES = [
  {
    id: 1,
    slug: 'article-1.html',
    title: '個人戦術とは何か',
    titleEn: 'What Is Individual Tactics?',
    category: 'Individual Tactics',
    categorySlug: 'individual',
    tags: ['個人戦術', 'ポジショニング', '認知'],
    excerpt: 'サッカーにおける「個人戦術」という概念を整理し、技術・フィジカルとの違いを明確にしながら、コーチが指導現場で応用できる形で体系化する。',
    date: '2025-01-15',
    readTime: '8 min',
    featured: true,
  },
  {
    id: 2,
    slug: 'article-2.html',
    title: 'マークの原則とは何か',
    titleEn: 'The Principles of Marking',
    category: 'Individual Tactics',
    categorySlug: 'individual',
    tags: ['マーク', '守備', '1対1'],
    excerpt: 'マークは単なる「相手についていく」行為ではない。ボール・相手・スペース・ゴールの関係性から導き出される原則を解説する。',
    date: '2025-01-22',
    readTime: '10 min',
    featured: false,
  },
  {
    id: 3,
    slug: 'article-3.html',
    title: 'カバーリングの原則とは何か',
    titleEn: 'The Principles of Covering',
    category: 'Individual Tactics',
    categorySlug: 'individual',
    tags: ['カバー', '守備', 'ポジショニング'],
    excerpt: 'カバーリングはリアクションではなく、予測に基づくアクションである。良いカバーポジションを取るための原則と、その背景にある論理を解説する。',
    date: '2025-01-29',
    readTime: '9 min',
    featured: false,
  },
  {
    id: 4,
    slug: 'article-4.html',
    title: 'なぜ失点分析が必要なのか',
    titleEn: 'Why Loss Analysis Matters',
    category: 'Analysis',
    categorySlug: 'analysis',
    tags: ['失点分析', '守備', 'データ'],
    excerpt: '勝利の分析だけでは見えないものがある。失点シーンの構造を解剖することで、チームの守備的脆弱性と改善の方向性が初めて明確になる。',
    date: '2025-02-05',
    readTime: '12 min',
    featured: false,
  },
  {
    id: 5,
    slug: 'article-5.html',
    title: '良いプレッシングとは何か',
    titleEn: 'What Makes a Good Press?',
    category: 'Principles',
    categorySlug: 'principles',
    tags: ['プレッシング', '守備原則', 'ハイプレス'],
    excerpt: 'プレッシングは「前から行く」という指示ではない。どこへ、いつ、なぜ、誰が――この4つの問いに答えられる原則的理解が真のプレッシングを生む。',
    date: '2025-02-12',
    readTime: '11 min',
    featured: false,
  },
];

const CATEGORIES = [
  { id: 'principles',   name: 'Principles',        nameJa: '攻守のトランジション原則',  count: 1 },
  { id: 'individual',   name: 'Individual Tactics', nameJa: '個人戦術の体系',           count: 3 },
  { id: 'training',     name: 'Training',           nameJa: 'トレーニング設計',          count: 0 },
  { id: 'analysis',     name: 'Analysis',           nameJa: '試合・失点分析',            count: 1 },
  { id: 'playmodels',   name: 'Play Models',        nameJa: 'プレーモデル解析',          count: 0 },
];
